management:
  endpoints:
    web:
      exposure:
        include: info, health, refresh

eureka:
  instance:
    prefer-ip-address: true # 서비스 이름 대신 서비스 IP 주소 등록 (책 기준)

  client:
    register-with-eureka: true # 유레카에 서비스 등록
    fetch-registry: true # 유레카 서비스 위치
    service-url:
      defaultZone: http://localhost:8761/eureka # 레지스트리 사본을 로컬로 가져오기

service:
  organization: service-organization
