example:
  property: "I AM THE LOCAL LICENSE SERVICE"

spring:
  datasource:
    initialization-mode: always
    platform: postgres
    schema: classpath:sql/schema-${spring.datasource.platform}.sql
    data: classpath:sql/data-${spring.datasource.platform}.sql

  cloud:
    stream:
      bindings:
#        input:
#          destination: organizationChangeTopic
#          content-type: application/json
#          group: licensingGroup
        inboundOrganizationChange:
          destination: organizationChangeTopic
          content-type: application/json
          group: licensingGroup
      kafka:
        binder:
          brokers: 192.168.0.6

  redis:
    host: 192.168.0.6
    port: 8379

logging:
  level:
    io.devfactory: debug