server:
  port: 0

spring:
  application:
    name: service-catalog

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      platform: h2
      data-locations: classpath:sql/data-${spring.sql.init.platform}.sql

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

  h2:
    console:
      enabled: true

  cloud:
    inetutils:
      ignored-interfaces:
        - eth1*

logging:
  level:
    io.devfactory: debug

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
