server:
  port: 0

spring:
  application:
    name: service-catalog

  sql:
    init:
      mode: always
      platform: mariadb
      data-locations: classpath:sql/data-${spring.sql.init.platform}.sql
      schema-locations: classpath:sql/schema-${spring.sql.init.platform}.sql

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    restart.enabled: false
    livereload.enabled: true

  config:
    import: configserver:http://localhost:8888/

  cloud:
    config:
      name: service-catalog
      profile: dev

    inetutils:
      ignored-interfaces:
        - eth1*

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: consumerGroupId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    io.devfactory: debug

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
