server:
  port: 8761

spring:
  application:
    name: server-eureka

# server 를 standalone 방식으로 띄움
eureka:
  client:
    register-with-eureka: false # 유레카 서비스에 자신을 등록하지 않음
    fetch-registry: false # 레지스트리 정보를 로컬에 캐싱하지 않음
    service-url:
      defaultZone: http://localhost:${server.port}/eureka

  server:
    # wait-time-in-ms-when-sync-empty: 60000 # 1분
    enable-self-preservation: false # 자기보호 설정 해제
