example:
  property: "I AM THE LOCAL ORGANIZATION SERVICE"

spring:
  datasource:
    initialization-mode: always
    platform: postgres
    schema: classpath:sql/schema-${spring.datasource.platform}.sql
    data: classpath:sql/data-${spring.datasource.platform}.sql

  cloud:
    stream:
      bindings:
        output:
          destination: organizationChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: 192.168.0.6

logging:
  level:
    io.devfactory: debug