spring:
  datasource:
    initialization-mode: always
    platform: postgres
    schema: classpath:sql/schema-${spring.datasource.platform}.sql
    data: classpath:sql/data-${spring.datasource.platform}.sql

logging:
  level:
    io.devfactory: debug