#hystrix:
#  command:
#    default:
#      execution.isolation.thread.timeoutInMilliseconds: 5000
#    service-license:
#      execution.isolation.thread.timeoutInMilliseconds: 7000
#
#service-license:
#  ribbon.ReadTimeout: 7000

logging:
  level:
    io.devfactory: debug

spring:
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://192.168.0.6:9411

